Add table of contents
alexgurr/react-coding-challenges pull request #15
Opened 2021-03-28 03:28 UTC by ma-shamshiri

## Proposed changes
I added a table of contents to make it easier to navigate README.md

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [.] Documentation Update (if none of the other choices apply)

2021-03-28 04:05 UTC, alexgurr commented
I like this idea, however have a few points:

- It seems this has broken a bunch of the headers - ![broken](https://puu.sh/Htc4o/3e0e6f84d9.png)
- I'd rather keep the bullet points consistent symbols (•)
- Not a big fan of the rainbow separator. Can we keep it consistent with the others?
- I'd put a `&nbsp;` above the `Table of Contents` headers, to be consistent with other headers

2021-03-28 12:58 UTC, alexgurr commented
Thanks for this. Will re-review in the morning and merge it if it's all ok.

2021-03-29 00:21 UTC, alexgurr commented
- Slack icon next to the community header still missing

- Arrows are still showing in the table of contents (is there a way around this?)

2021-03-29 02:11 UTC, ma-shamshiri commented
Thank you Alex for your comment.
I just added the Slack icon next to the community header.
Also, the arrows have been removed from the table of contents.

2021-03-29 03:00 UTC, alexgurr requested changes

2021-03-29 03:00 UTC, alexgurr commented on README.md
> +  <summary>Table of Contents</summary>
```suggestion
```

2021-03-29 03:02 UTC, alexgurr commented
For some reason the first entry always shows an arrow ![screen](https://puu.sh/HtrTu/61b695659d.png)

2021-03-29 03:39 UTC, ma-shamshiri commented
Well, the reason the first arrow is displayed is that I used the <details> tag for the table of contents. 
In this case, the user can open and close the table of contents.
Actually <details> tag is basically used to create an interactive widget that one can open and close. 
Do you want me to remove it?

2021-03-29 05:23 UTC, alexgurr commented
I don't think it needs to be closable, I think we can just make it static.

2021-03-29 05:36 UTC, ma-shamshiri commented
That's right.
I just removed the "details" tag.

2021-03-29 05:45 UTC, alexgurr commented
- Everything after the table of contents is inlined (tabbed in) 

&nbsp;
![screen](https://puu.sh/HttDd/74c05a03d6.png)

- There's no space/line break between the bullets and afterword

&nbsp;
![screen2](https://puu.sh/HttEv/c2bf7ff676.png)

2021-03-29 05:51 UTC, ma-shamshiri commented
Yes, you are right, sometimes this problem occurs due to improper indentation. 
Is it fine now?

2021-03-29 06:04 UTC, alexgurr commented
So I've just realised GitHub provides a table of contents out the box, no custom TOC required. This means we no longer have to keep the TOC updated or use HTML in the readme file. Let me know if there's anything else your PR provides, otherwise I'm closing this for now. 

![screengrab](https://puu.sh/HttRc/453a5a7da6.gif)

2021-03-29 06:04 UTC, closed without merging